export interface ILocalProcessEnv {
  DB_PORT: number;
  DB_HOST: string;
  DB_NAME: string;
  DB_PASSWORD: string;
}

export enum SimRegistrationTypes {
  SIM_REG = 'SIM_REG',
  SIM_SWAP = 'SIM_SWAP',
}

export enum SimTypes {
  PHYSICAL_SIM = 'PHYSICAL',
  ELECTRONIC_SIM = 'E_SIM',
}

export enum UserIdentityTypes {
  NATIONAL = 'NATIONAL',
  FOREIGN_WITH_NIN = 'FOREIGN_WITH_NIN',
  FOREIGN_WITHOUT_NIN = 'FOREIGN_WITHOUT_NIN',
}

export enum NinTypes {
  NIN = 'NIN',
  VNIN = 'VNIN',
}

export enum NewRegistrationTypes {
  REGISTER_WITH_SERIAL_NUMBER = 'REGISTER_WITH_SERIAL_NUMBER',
  REGISTER_WITH_MSISDN = 'REGISTER_WITH_MSISDN',
}

export enum DisabilityTypes {
  PHYSICAL_DISABILITY_FEET = 'PHYSICAL_DISABILITY_FEET',
  PHYSICAL_DISABILITY_ARM = 'PHYSICAL_DISABILITY_ARM',
  MENTAL_AND_HEALTH_RELATED = 'MENTAL_AND_HEALTH_RELATED',
  VISION_IMPAIRMENT_BOTH_EYES = 'VISION_IMPAIRMENT_BOTH_EYES',
  VISION_IMPAIRMENT_RIGHT_EYE = 'VISION_IMPAIRMENT_RIGHT_EYE',
  VISION_IMPAIRMENT_LEFT_EYE = 'VISION_IMPAIRMENT_LEFT_EYE',
  SPEECH_IMPAIRMENT = 'SPEECH_IMPAIRMENT',
  DEAF = 'DEAF',
}

export enum GenderTypes {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHERS = 'OTHERS',
}

export enum ReligionTypes {
  ISLAM = 'ISLAM',
  CHRISTIANITY = 'CHRISTIANITY',
  TRADITIONAL = 'TRADITIONAL',
  OTHERS = 'OTHERS',
}

export enum SimServiceTypes {
  VOICE_SIM = 'VOICE_SIM',
  DATA_SIM = 'DATA_SIM',
}

export enum SimSwapTypes {
  SIM_CHANGE = 'SIM_CHANGE',
  SIM_UPGRADE = 'SIM_UPGRADE',
}

export enum ReasonForSimChangeTypes {
  '4G_UPGRADE' = '4G_UPGRADE',
  RESIZE_SIM = 'RESIZE_SIM',
}
